### ISSUE TITLE
Timeout error in both Linux and Lando/Docker environments

### ISSUE THREAD

**Issue by zahardev** [hummal/crittr#31]
**Describe the bug**
Maybe this is a puppeteer problem. I managed to run puppeteer in this environment (please see the script below), but Crittr still shows "TimeoutError: Navigation timeout of 30000 ms exceeded".

**To Reproduce**
1. Create a Lando config file

.lando.yml:
```
name: crittr
services:
  node:
    type: node
    build_as_root:
      - apt update
      - apt install -y fonts-liberation gconf-service libappindicator1 libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgbm-dev libgdk-pixbuf2.0-0 libgtk-3-0 libicu-dev libjpeg-dev libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libpng-dev libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 xdg-utils

tooling:
  npm:
    service: node
```

2. Create test.js file:

I initialized the puppeteer first to make sure that the browser can run correctly. Browser correctly opens GitHub and makes the screenshot.

```
const puppeteer = require('puppeteer');
const Crittr = require( "crittr" );

(async () => {
	const browser = await puppeteer.launch({headless: true, args: ['--no-sandbox']});
	const page = await browser.newPage();
	await page.goto('https://github.com/');
	await page.screenshot({ path: 'test.png' });

	try {
		await Crittr({
			puppeteer: {
				browser: browser
			},
			urls: ['https://github.com/'],
			css: `.header-logo-invertocat {
            margin: -1px 15px -1px -2px;
            color: #fff;
            white-space: nowrap;
        }`,
			device: {
				width: 1920,
				height: 1080,
			},
		})
	} catch(err){
		console.error(err);
	}


	await browser.close();
})();
```

3. Run container:

`lando start`

4. Create package.json:
```
{
  "name": "lando-crittr",
  "version": "1.0.0",
  "description": "Node Web Server with Lando & Crittr",
  "license": "MIT",
  "dependencies": {
    "crittr": "^1.4.0",
    "puppeteer": "^13.0.1"
  },
  "scripts": {
    "test": "node ./test.js"
  }
}
```

5. Install dependencies:
`lando npm install`

6. Run script:
`lando npm run test`

**Expected behavior**
Script should generate CSS file.

**Current behavior**
The script can run puppeteer, and can create screenshots of GitHub - so it means that Chromium works correctly.
But when it comes to Crittr, it shows timeout error:  `TimeoutError: Navigation timeout of 30000 ms exceeded. Could not get critical ast for url https://github.com/`

**Screenshots**

![2022-01-12-b974](https://user-images.githubusercontent.com/5578322/149113658-9cb75be2-cb9c-4849-8830-775f40f03f6c.png)

**Environment (please complete the following information):**
 - Lando 3.6.0
 - Node.js v14.18.3
